# List

In [96]:
a = ["h","e","l","l","o"]

In [97]:
#1
a.insert(1,"cool")  # 2 arguments. the first for position, the second for element.

In [98]:
a

['h', 'cool', 'e', 'l', 'l', 'o']

In [99]:
#2
a.append("ya")

In [100]:
a

['h', 'cool', 'e', 'l', 'l', 'o', 'ya']

In [101]:
#3
a.remove("ya")

In [102]:
a

['h', 'cool', 'e', 'l', 'l', 'o']

In [103]:
#4
a.extend([1,2])

In [104]:
a

['h', 'cool', 'e', 'l', 'l', 'o', 1, 2]

In [64]:
def takeSecond(elem):
    return elem[1]

random = [(2, 2), (3, 4), (4, 1), (1, 3)]

In [65]:
random.sort(key = takeSecond)  # key竟然可以是一個function, cool! 

In [66]:
random

[(4, 1), (2, 2), (1, 3), (3, 4)]

In [67]:
random.reverse()

In [68]:
random

[(3, 4), (1, 3), (2, 2), (4, 1)]

# unpacking

In [11]:
points = [(1,2),(1.3,-4),(2.1,5)]
x,y = zip(*points)         # *有點像是解開的感覺

In [12]:
x

(1, 1.3, 2.1)

In [13]:
y

(2, -4, 5)

In [28]:
[x[0] for x in points]  # 這樣也行！

[1, 1.3, 2.1]

# Dictionary

In [24]:
dictionary = dict(a="3",
                  b="4",
                  c="hi"
                
                 )

In [25]:
dictionary

{'a': '3', 'b': '4', 'c': 'hi'}

# Set & collections.defaultdict

In [30]:
# 沒有順序，每個值都是unique

In [1]:
from collections import defaultdict

In [8]:
s = [('red', 1), ('blue', 2), ('red', 3), ('blue', 4), ('red', 1), ('blue', 4)]
d = defaultdict(set)
for k,v in s:
    d[k].add(v)     # set時要用add，不是append

In [9]:
d

defaultdict(set, {'blue': {2, 4}, 'red': {1, 3}})

In [25]:
list(d.items())[0]

('red', {1, 3})

# collections.Counter

In [1]:
import collections

In [2]:
c = collections.Counter("HelloWorld")

In [3]:
c

Counter({'H': 1, 'W': 1, 'd': 1, 'e': 1, 'l': 3, 'o': 2, 'r': 1})

In [29]:
c.most_common(3)

[('l', 3), ('o', 2), ('e', 1)]

In [34]:
cnt = collections.Counter()
for word in ["red","blue","red","green","black","blue","red"]:
    cnt[word] +=1

In [35]:
cnt

Counter({'black': 1, 'blue': 2, 'green': 1, 'red': 3})

# 以下都是這個網頁的一些東西！ https://chrisalbon.com/   

### Text

In [1]:
text = "Chapter 1"

In [4]:
format(text, ">20")

'           Chapter 1'

In [14]:
format(text,"o^20")

'oooooChapter 1oooooo'

In [19]:
format(text, "r<20")

'Chapter 1rrrrrrrrrrr'

### chain together list 

In [21]:
from itertools import chain

In [22]:
allies = ["a","b","c","d"]
enemies = ["A","B","C","D"]

In [23]:
for i in chain(allies, enemies):
    print(i)

a
b
c
d
A
B
C
D


### Compare Two Dictionaries

In [25]:
importers = dict(elslvador = 1234, spain=2345, france = 3456)
exporters = dict(tw = 1023, us =23113, en = 1393,spain=2345)

In [26]:
importers.keys() & exporters.keys()  # 找出共同的keys

{'spain'}

In [30]:
importers.items()&exporters.items()   # 找出共同的 items

{('spain', 2345)}

In [28]:
importers.keys() - exporters.keys()

{'elslvador', 'france'}

### Convert HTML Characters To Strings


In [32]:
import html

In [33]:
text = "The item costs &#165;400 or &#163;4."

In [34]:
html.unescape(text)

'The item costs ¥400 or £4.'

In [35]:
html.escape(text)

'The item costs &amp;#165;400 or &amp;#163;4.'

### Create A New File Then Write To It


In [36]:
# write
with open("test.txt","xt") as f:
    f.write("hello")

In [38]:
# read
with open("test.txt", "rt") as f:
    data = f.read()

In [39]:
data

'hello'

In [ ]:
# delete the file
import os
os.remove("test.txt")

### Find The Max Value In A Dictionary


In [47]:
ages = dict(John=15, David=3, alex=20, Judy=24)

In [48]:
max(zip(ages.values(),ages.keys()))

(24, 'Judy')

### Formatting Numbers


In [51]:
annual_revenue = 9282904.9282872782

In [52]:
format(annual_revenue, "0.2f")

'9282904.93'

In [54]:
format(annual_revenue, "0.2%")

'928290492.83%'

In [56]:
format(annual_revenue, ",.1f")

'9,282,904.9'

In [57]:
format(annual_revenue, "e")

'9.282905e+06'

### Hard Wrapping Text

In [59]:
import textwrap

In [58]:
excerpt = 'Then there was the bad weather. It would come in one day when the fall was over. We would have to shut the windows in the night against the rain and the cold wind would strip the leaves from the trees in the Place Contrescarpe. The leaves lay sodden in the rain and the wind drove the rain against the big green autobus at the terminal and the Café des Amateurs was crowded and the windows misted over from the heat and the smoke inside.'

In [61]:
print(textwrap.fill(excerpt,100))  # 100就是說一個row有100個字

Then there was the bad weather. It would come in one day when the fall was over. We would have to
shut the windows in the night against the rain and the cold wind would strip the leaves from the
trees in the Place Contrescarpe. The leaves lay sodden in the rain and the wind drove the rain
against the big green autobus at the terminal and the Café des Amateurs was crowded and the windows
misted over from the heat and the smoke inside.


### Iterate Over Multiple Lists Simultaneously


In [62]:
names = ["James","Bob","Sarah","Marco","Nancy","Sally"]
ages = [42,13,14,25,63,23]

In [63]:
for name, age in zip(names,ages):
    print(name,age)

James 42
Bob 13
Sarah 14
Marco 25
Nancy 63
Sally 23


### Priority Queues


### Streaming Data Pipeline


In [137]:
raw_data = list(range(1,11,1))

In [138]:
# Define a generator that yields input+6
def add_6(numbers):
    for x in numbers:
        output = x+6
        yield output

# Define a generator that yields input-2
def subtract_2(numbers):
    for x in numbers:
        output = x-2
        yield output

# Define a generator that yields input*100        
def multiply_by_100(numbers):
    for x in numbers:
        output = x*100
        yield output

In [139]:
# Step 1 of the pipeline
step1 = add_6(raw_data)

# Step 2 of the pipeline
step2 = subtract_2(step1)

# Step 3 of the pipeline
pipeline = multiply_by_100(step2)

In [140]:
next(pipeline)

500

### Construct A Dictionary From Multiple Lists


In [142]:
officer_names = ['Sodoni Dogla', 'Chris Jefferson', 'Jessica Billars', 'Michael Mulligan', 'Steven Johnson']
officer_armies = ['Purple Army', 'Orange Army', 'Green Army', 'Red Army', 'Blue Army']


In [143]:
dict(zip(officer_names, officer_armies))

{'Chris Jefferson': 'Orange Army',
 'Jessica Billars': 'Green Army',
 'Michael Mulligan': 'Red Army',
 'Sodoni Dogla': 'Purple Army',
 'Steven Johnson': 'Blue Army'}

### Iterating Over Dictionary Keys

In [147]:
Officers = {'Michael Mulligan': 'Red Army',
            'Steven Johnson': 'Blue Army',
            'Jessica Billars': 'Green Army',
            'Sodoni Dogla': 'Purple Army',
            'Chris Jefferson': 'Orange Army'}

In [150]:
for k in Officers:
    print(k)

Chris Jefferson
Sodoni Dogla
Steven Johnson
Michael Mulligan
Jessica Billars


In [153]:
{keys:Officers[keys] for keys in Officers if not keys.startswith("Chris")}    # for i in... if not ...

{'Jessica Billars': 'Green Army',
 'Michael Mulligan': 'Red Army',
 'Sodoni Dogla': 'Purple Army',
 'Steven Johnson': 'Blue Army'}

### All Combinations For A List Of Objects


In [184]:
from itertools import combinations_with_replacement

In [185]:
list_of_objects = ["warplane","armor","infantry"]

In [186]:
combinations = []

In [187]:
for i in list(range(len(list_of_objects))):
    combinations.append(list(combinations_with_replacement(list_of_objects, i+1)))

In [188]:
combinations

[[('warplane',), ('armor',), ('infantry',)],
 [('warplane', 'warplane'),
  ('warplane', 'armor'),
  ('warplane', 'infantry'),
  ('armor', 'armor'),
  ('armor', 'infantry'),
  ('infantry', 'infantry')],
 [('warplane', 'warplane', 'warplane'),
  ('warplane', 'warplane', 'armor'),
  ('warplane', 'warplane', 'infantry'),
  ('warplane', 'armor', 'armor'),
  ('warplane', 'armor', 'infantry'),
  ('warplane', 'infantry', 'infantry'),
  ('armor', 'armor', 'armor'),
  ('armor', 'armor', 'infantry'),
  ('armor', 'infantry', 'infantry'),
  ('infantry', 'infantry', 'infantry')]]

In [194]:
[i for row in combinations for i in row]  ## flattend! 好神奇的語法 注意, 順序有差喔

[('warplane',),
 ('armor',),
 ('infantry',),
 ('warplane', 'warplane'),
 ('warplane', 'armor'),
 ('warplane', 'infantry'),
 ('armor', 'armor'),
 ('armor', 'infantry'),
 ('infantry', 'infantry'),
 ('warplane', 'warplane', 'warplane'),
 ('warplane', 'warplane', 'armor'),
 ('warplane', 'warplane', 'infantry'),
 ('warplane', 'armor', 'armor'),
 ('warplane', 'armor', 'infantry'),
 ('warplane', 'infantry', 'infantry'),
 ('armor', 'armor', 'armor'),
 ('armor', 'armor', 'infantry'),
 ('armor', 'infantry', 'infantry'),
 ('infantry', 'infantry', 'infantry')]

### Apply Operations Over Items In A List


In [201]:
battleDeaths = [482,93,392,920,813,199,374,237,244]

In [202]:
def updated(x): return x+100

In [203]:
# method1
list(map(updated,battleDeaths))

[582, 193, 492, 1020, 913, 299, 474, 337, 344]

In [204]:
# method2
# create another empty list and use it to append objects

In [205]:
# method3
list(map(lambda x:x+100, battleDeaths))

[582, 193, 492, 1020, 913, 299, 474, 337, 344]

In [207]:
# method4
[x+100 for x in battleDeaths]   # very succint and simple !

[582, 193, 492, 1020, 913, 299, 474, 337, 344]

### Arithmetic Basics

In [210]:
5/3

1.6666666666666667

In [209]:
5//3  # 高斯函數

1

In [217]:
5%3  # 除以完之後.. 剩下的餘數

2

### Breaking Up String Variables


In [221]:
a,b,c,d  = "hola"

In [222]:
a # OMG, so convenient

'h'

In [223]:
a,*b = "spain"

In [224]:
a

's'

In [225]:
b

['p', 'a', 'i', 'n']

### Cartesian Product


In [14]:
import pandas as pd
import itertools

In [13]:
i = [1,2,3,4,5]
j = [1,2,3,4,5]

In [12]:
# method1
[(x,y) for x in i for y in j][:3]

[(1, 1), (1, 2), (1, 3)]

In [16]:
# method2
for i in itertools.product([1,2,3,4,5],[1,2,3,4,5]):
    print(i)
    break

(1, 1)


### Continue And Break Loops


In [61]:
import random

In [62]:
running = True

In [63]:
while running:
    
    s = random.randint(0,5)
    if s<3:
        print("too small")
        print(s)
        continue            # 直接跳回迴圈
    if s==4:
        running = False
        print("good, stop")
    if s==5:
        print("It's 5, break!")
        break

It's 5, break!


### Data structure basics

In [70]:
# dictionary

In [71]:
staff = {'Chris' : 'chris@stater.org',
         'Jake' : 'jake@stater.org',
         'Ashley' : 'ashley@stater.org',
         'Shelly' : 'shelly@stater.org'
        }

In [73]:
staff["Guido"] = "guido@python.org" ; staff["Guido"]

'guido@python.org'

In [75]:
# sets ,  unordered collections of simple objects.

In [84]:
BRI = set(['brazil', 'russia', 'india'])

In [85]:
BRIC = BRI.copy()   # 當要指定一個 mutable的東西到另一個東西，則可以用 copy 才不會一起更動到原本的東西

In [86]:
BRIC.add("china")

In [88]:
BRIC.issuperset(BRI)

True

In [89]:
BRI&BRIC

{'brazil', 'india', 'russia'}

### Date And Time Basics


In [94]:
from datetime import datetime
from datetime import timedelta 

In [97]:
now = datetime.now()  ; now

datetime.datetime(2017, 9, 11, 23, 18, 28, 56587)

In [101]:
now.year

2017

In [99]:
datetime(2014, 5, 11, 20 ,5, 11, 688051)

datetime.datetime(2014, 5, 11, 20, 5, 11, 688051)

In [111]:
delta = datetime(2011,1,7) - datetime(2011,1,6)

In [112]:
delta.days, delta.seconds

(1, 0)

### Dictionary Basics


In [115]:
who_org = {}
who_org['name'] = 'WHO'
who_org['staff'] = '10'
who_org['url'] = 'http://who.org'

In [116]:
who_org

{'name': 'WHO', 'staff': '10', 'url': 'http://who.org'}

### Enumerate A List


In [117]:
data = ["one", "two", "three", "four", "five"]

In [119]:
for item in enumerate(data):
    print(item)
    print(item[1])

(0, 'one')
one
(1, 'two')
two
(2, 'three')
three
(3, 'four')
four
(4, 'five')
five


### Function Basics

In [121]:
def print_max(x,y):
    if x>y:
        print(x)
    elif x==y:
        print(x, "is equal to", y)
    else:
        print(y)

In [124]:
print_max(3,3)

3 is equal to 3


In [125]:
# Note: By default, variables created within functions are local to the function. 
# But you can create a global function that IS defined outside the function.

In [129]:
x = 50

In [130]:
def func():
    # global variable
    global x
    
    print(x)
    
    x = 2
    
    print("change global x to ..", x)

In [131]:
func()

50
change global x to .. 2


In [132]:
print(x)

2


In [133]:
# Create Function Say() Displaying x with default value of 1

In [136]:
def say(x, times=1, times2 = 3):
    print(x*times, x*times2)

In [137]:
say("@")

@ @@@


In [138]:
# VarArgs Parameters (i.e. unlimited number of parameters)

In [4]:
def total(initial=5, *numbers, **keywords):
    count = initial
    
    for number in numbers:
        count += number
    for key in keywords:
        count += keywords[key]
    
    return count

In [12]:
total(10,1,2,3,vegetables=50, fruits=100)


166

### Generating Random Numbers With Numpy


In [13]:
import numpy as np

In [15]:
#  Random Number From The Normal Distribution
np.random.normal()

1.6149999073351433

In [17]:
np.random.normal(size=(3,2))

array([[-0.53319731, -0.41137274],
       [ 0.54395508,  1.32422808],
       [-1.26810059,  0.75884045]])

In [32]:
# Random Numbers From The Uniform Distribution
np.random.uniform(size = 4, low=5, high=6)                # 這裡的low, high是...  [low, high)

array([ 5.15247305,  5.91895023,  5.90826194,  5.18000096])

In [33]:
# Random Integers Between 1 and 100
np.random.randint(low=1, high=100, size=4)

array([23, 73, 30, 45])

### If Else On Any Or All Elements


In [34]:
import pandas as pd
data = {"score":[1,2,3,4,5]}

In [35]:
d = pd.DataFrame(data)

In [36]:
d

score
0      1
1      2
2      3
3      4
4      5

In [38]:
if (d.score==3).any():
    print("hi")

hi


In [39]:
if (d.score==3).all():
    print("wow")
else:
    print("poo")

poo


### Indexing And Slicing Numpy Arrays


In [40]:
import numpy as np
battleDeaths = np.array([1245, 2732, 3853, 4824, 5292, 6184, 7282, 81393, 932, 10834])

In [43]:
a = battleDeaths[:3]
b = battleDeaths[3:7]
c = battleDeaths[7:]

In [55]:
a[0] = 1    # any changes to the new variable are broadcasted to the original variable

battleDeaths

array([    1,  2732,  3853,  4824,  5292,  6184,  7282, 81393,   932, 10834])

In [51]:
regimentNames = ['Nighthawks', 'Sky Warriors', 'Rough Riders', 'New Birds']
regimentNumber = [1, 2, 3, 4]
regimentSize = [1092, 2039, 3011, 4099]
regimentCommander = ['Mitchell', 'Blackthorn', 'Baker', 'Miller']

regiments = np.array([regimentNames, regimentNumber, regimentSize, regimentCommander])
regiments

array([['Nighthawks', 'Sky Warriors', 'Rough Riders', 'New Birds'],
       ['1', '2', '3', '4'],
       ['1092', '2039', '3011', '4099'],
       ['Mitchell', 'Blackthorn', 'Baker', 'Miller']], 
      dtype='<U12')

In [52]:
regiments[:,0]

array(['Nighthawks', '1', '1092', 'Mitchell'], 
      dtype='<U12')

In [54]:
regiments[:2,2:]

array([['Rough Riders', 'New Birds'],
       ['3', '4']], 
      dtype='<U12')